kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-setup-configmap
data:
  gelf.conf: |
    input {
      gelf {
        port => 12201
      }
    }
    output {
      stdout {}
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }

